// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Demo.proto

package xyz.yann.grpc.proto;

public final class DemoProto {
  private DemoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xyz_yann_grpc_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xyz_yann_grpc_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_xyz_yann_grpc_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_xyz_yann_grpc_proto_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nDemo.proto\022\023xyz.yann.grpc.proto\"\031\n\tMyR" +
      "equest\022\014\n\004uuid\030\001 \001(\t\"\032\n\nMyResponse\022\014\n\004re" +
      "sp\030\001 \001(\t2^\n\013DemoService\022O\n\010sayHello\022\036.xy" +
      "z.yann.grpc.proto.MyRequest\032\037.xyz.yann.g" +
      "rpc.proto.MyResponse\"\0000\001B\"\n\023xyz.yann.grp" +
      "c.protoB\tDemoProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_xyz_yann_grpc_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_xyz_yann_grpc_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xyz_yann_grpc_proto_MyRequest_descriptor,
        new java.lang.String[] { "Uuid", });
    internal_static_xyz_yann_grpc_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_xyz_yann_grpc_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_xyz_yann_grpc_proto_MyResponse_descriptor,
        new java.lang.String[] { "Resp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
