// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Demo.proto

package xyz.yann.grpc.proto;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xyz.yann.grpc.proto.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string resp = 1;</code>
   * @return The resp.
   */
  java.lang.String getResp();
  /**
   * <code>string resp = 1;</code>
   * @return The bytes for resp.
   */
  com.google.protobuf.ByteString
      getRespBytes();
}
