// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Demo.proto

package xyz.yann.grpc.proto;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:xyz.yann.grpc.proto.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   * @return The uuid.
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   * @return The bytes for uuid.
   */
  com.google.protobuf.ByteString
      getUuidBytes();
}
